/**
 * Created by Mihail.Rybalka on 15.11.13.
 */

var countryObject = {
    'AC' :'остров Вознесения',
    'AD' : 'Андорра',
    'AE' : 'Объединенные Арабские Эмираты',
    'AF' : 'Афганистан',
    'AG' : 'Антигуа и Барбуда',
    'AL' : 'Албания',
    'AM' : 'Армения',
    'AN' : 'Голланские Антильские острова',
    'AO' : 'Ангола',
    'AQ' : 'Антарктика',
    'AR' : 'Аргентина',
    'AS' : 'Американское Самоа',
    'AT' : 'Австрия',
    'AU' : 'Австралия',
    'AW' : 'Аруба',
    'AX' : 'Аландские острова',
    'AZ' : 'Азербайджан',
    'BA' : 'Босния и Герцеговина',
    'BB' : 'Барбадос',
    'BD' : 'Бангладеш',
    'BE' : 'Бельгия',
    'BF' : 'Буркина-Фасо',
    'BG' : 'Болгария',
    'BH' : 'Бахрейн',
    'BI' : 'Бурунди',
    'BJ' : 'Бенин',
    'BM' : 'Бермудские острова',
    'BN' : 'Бруней',
    'BO' : 'Боливия',
    'BR' : 'Бразилия',
    'BS' : 'Багамские острова',
    'BT' : 'Бутан',
    'BW' : 'Ботсвана',
    'BY' : 'Беларусь',
    'BZ' : 'Белиз',
    'CA' : 'Канада',
    'CC' : 'Кокосовые острова',
    'CD' : 'Конго',
    'CF' : 'Центральноафриканская Республика',
    'CG' : 'Конго',
    'CH' : 'Швейцария',
    'CI' : 'Кот-дИвуар',
    'CK' : 'острова Кука',
    'CL' : 'Чили',
    'CM' : 'Камерун',
    'CN' : 'Китай',
    'CO' : 'Колумбия',
    'CR' : 'Коста-Рика',
    'CS' : 'Сербия и Черногория',
    'CU' : 'Куба',
    'CV' : 'Кабо-Верде',
    'CX' : 'остров Рождества',
    'CY' : 'Кипр',
    'CZ' : 'Чехия',
    'DE' : 'Германия',
    'DJ' : 'Джибути',
    'DK' : 'Дания',
    'DM' : 'Доминика',
    'DO' : 'Доминиканская Республика',
    'DZ' : 'Алжир',
    'EC' : 'Эквадор',
    'EE' : 'Эстония',
    'EG' : 'Египет',
    'EH' : 'Западная Сахара',
    'ER' : 'Эритрея',
    'ES' : 'Испания',
    'ET' : 'Эфиопия',
    'FI' : 'Финляндия',
    'FJ' : 'Фиджи',
    'FK' : 'Фолклендские острова',
    'FM' : 'Микронезия',
    'FO' : 'Фарерские острова',
    'FR' : 'Франция',
    'GA' : 'Габон',
    'GB' : 'Соединенное Королевство Великобритании и Северной Ирландии',
    'GD' : 'Гренада',
    'GE' : 'Грузия',
    'GF' : 'Французская Гвиана',
    'GG' : 'остров Гернси',
    'GH' : 'Гана',
    'GI' : 'Гибралтар',
    'GL' : 'Гренландия',
    'GM' : 'Гамбия',
    'GN' : 'Гвинея',
    'GP' : 'Гваделупа',
    'GQ' : 'Экваториальная Гвинея',
    'GR' : 'Греция',
    'GS' : 'Южная Джорджия и Южные Сандвичевы острова',
    'GT' : 'Гватемала',
    'GU' : 'Гуам',
    'GW' : 'Гвинея-Бисау',
    'GY' : 'Гайана',
    'HK' : 'Гонконг',
    'HN' : 'Гондурас',
    'HR' : 'Хорватия',
    'HT' : 'Гаити',
    'HU' : 'Венгрия',
    'ID' : 'Индонезия',
    'IE' : 'Ирландия',
    'IL' : 'Израиль',
    'IM' : 'остров Мэн',
    'IN' : 'Индия',
    'IQ' : 'Ирак',
    'IR' : 'Иран',
    'IS' : 'Исландия',
    'IT' : 'Италия',
    'JE' : 'остров Джерси',
    'JM' : 'Ямайка',
    'JO' : 'Иордания',
    'JP' : 'Япония',
    'KE' : 'Кения',
    'KG' : 'Кыргызстан',
    'KH' : 'Камбоджа',
    'KI' : 'Кирибати',
    'KM' : 'Коморские острова',
    'KN' : 'Сент-Китс и Невис',
    'KP' : 'Северная Корея',
    'KR' : 'Южная Корея',
    'KW' : 'Кувейт',
    'KY' : 'Каймановы острова',
    'KZ' : 'Казахстан',
    'LA' : 'Лаос',
    'LB' : 'Ливан',
    'LC' : 'Сент-Люсия',
    'LI' : 'Лихтенштейн',
    'LK' : 'Шри-Ланка',
    'LR' : 'Либерия',
    'LS' : 'Лесото',
    'LT' : 'Литва',
    'LU' : 'Люксембург',
    'LV' : 'Латвия',
    'LY' : 'Ливия',
    'MA' : 'Марокко',
    'MC' : 'Монако',
    'ME' : 'Монтенегро',
    'MD' : 'Молдова',
    'MG' : 'Мадагаскар',
    'MH' : 'Маршалловы острова',
    'MK' : 'Македония',
    'ML' : 'Мали',
    'MM' : 'Мьянма',
    'MN' : 'Монголия',
    'MO' : 'Макао',
    'MP' : 'Mariana  Северные Марианские острова',
    'MQ' : 'Мартиника',
    'MR' : 'Мавритания',
    'MS' : 'Монтсеррат',
    'MT' : 'Мальта',
    'MU' : 'Маврикий',
    'MV' : 'Мальдивы',
    'MW' : 'Малави',
    'MX' : 'Мексика',
    'MY' : 'Малайзия',
    'MZ' : 'Мозамбик',
    'NA' : 'Намибия',
    'NC' : 'Новая Каледония',
    'NE' : 'Нигер',
    'NF' : 'Норфолк',
    'NG' : 'Нигерия',
    'NI' : 'Никарагуа',
    'NL' : 'Нидерланды',
    'NO' : 'Норвегия',
    'NP' : 'Непал',
    'NR' : 'Науру',
    'NZ' : 'Новая Зеландия',
    'OM' : 'Оман',
    'PA' : 'Панама',
    'PE' : 'Перу',
    'PF' : 'Французская Полинезия',
    'PG' : 'Папуа - Новая Гвинея',
    'PH' : 'Филиппины',
    'PK' : 'Пакистан',
    'PL' : 'Польша',
    'PM' : 'Сен-Пьер и Микелон',
    'PN' : 'остров Питкэрн',
    'PR' : 'Пуэрто-Рико',
    'PS' : 'Палестина',
    'PT' : 'Португалия',
    'PW' : 'Палау',
    'PY' : 'Парагвай',
    'QA' : 'Катар',
    'RE' : 'остров Реюньон',
    'RO' : 'Румыния',
    'RU' : 'Россия',
    'RW' : 'Руанда',
    'SA' : 'Саудовская Аравия',
    'SB' : 'Соломоновы Острова',
    'SC' : 'Сейшельские Острова',
    'SD' : 'Судан',
    'SE' : 'Швеция',
    'SG' : 'Сингапур',
    'SH' : 'остров Святой Елены',
    'SI' : 'Словения',
    'SK' : 'Словакия',
    'SL' : 'Сьерра-Леоне',
    'SM' : 'Сан-Марино',
    'SN' : 'Сенегал',
    'SO' : 'Сомали',
    'SR' : 'Суринам',
    'ST' : 'Сан-Томе и Принсипи',
    'SU' : 'СССР',
    'SV' : 'Сальвадор',
    'SY' : 'Сирия',
    'SZ' : 'Свазиленд',
    'TD' : 'Чад',
    'TG' : 'Того',
    'TH' : 'Таиланд',
    'TJ' : 'Таджикистан',
    'TK' : 'Токелау',
    'TM' : 'Туркменистан',
    'TN' : 'Тунис',
    'TO' : 'Тонга',
    'TP' : 'Восточный Тимор',
    'TR' : 'Турция',
    'TT' : 'Тринидад и Тобаго',
    'TV' : 'Тувалу',
    'TW' : 'Тайвань',
    'TZ' : 'Танзания',
    'UA' : 'Украина',
    'UG' : 'Уганда',
    'UK' : 'Великобритания',
    'US' : 'США',
    'UY' : 'Уругвай',
    'UZ' : 'Узбекистан',
    'VA' : 'Ватикан',
    'VC' : 'Сент-Винсент и Гренадины',
    'VE' : 'Венесуэла',
    'VG' : 'Виргинские острова, Британские',
    'VI' : 'Виргинские острова, США',
    'VN' : 'Вьетнам',
    'VU' : 'Вануату',
    'WS' : 'Западное Самоа',
    'YE' : 'Йемен',
    'YU' : 'Югославия',
    'ZA' : 'ЮАР',
    'ZM' : 'Замбия',
    'ZW' : 'Зимбабве'
};

function getKeyByCountry(countryName)
{
    for (key in countryObject) {
        if (countryName == countryObject[key]) {
            return key;
        }
    }
    return null;
}

var countryListByLevel = [
    [
        countryObject.RU,
        countryObject.BY,
        countryObject.BR,
        countryObject.UA,
        countryObject.UK,
        countryObject.US,
        countryObject.ES,
        countryObject.JP,
        countryObject.CN,
        countryObject.IT,
        countryObject.FR,
        countryObject.DE
    ],
    [
        countryObject.CN,
        countryObject.CO,
        countryObject.CZ,
        countryObject.DE,
        countryObject.FR,
        countryObject.IN,
        countryObject.IT,
        countryObject.KR
    ],
    [
        countryObject.AT,
        countryObject.AU,
        countryObject.AE,
        countryObject.ZA,
        countryObject.TR,
        countryObject.RO,
        countryObject.DK,
        countryObject.SE
    ],
    [
        countryObject.PT,
        countryObject.SA,
        countryObject.NZ,
        countryObject.NL,
        countryObject.NO,
        countryObject.PL,
        countryObject.MX,
        countryObject.KP
    ],
    [
        countryObject.KZ,
        countryObject.LA,
        countryObject.LB,
        countryObject.AF,
        countryObject.BO,
        countryObject.AZ,
        countryObject.BA,
        countryObject.CA
    ],
    [
        countryObject.CH,
        countryObject.CI,
        countryObject.CL,
        countryObject.CU,
        countryObject.DK,
        countryObject.EG,
        countryObject.FI,
        countryObject.GE
    ],
    [
        countryObject.GR,
        countryObject.HK,
        countryObject.HR,
        countryObject.HU,
        countryObject.ID,
        countryObject.IE,
        countryObject.IL,
        countryObject.IQ
    ],
    [
        countryObject.JM,
        countryObject.LT,
        countryObject.MC,
        countryObject.MG,
        countryObject.MN,
        countryObject.MV,
        countryObject.MY,
        countryObject.NP
    ],
    [
        countryObject.OM,
        countryObject.PA,
        countryObject.PE,
        countryObject.PH,
        countryObject.PK,
        countryObject.PY,
        countryObject.QA,
        countryObject.SI
    ],
    [
        countryObject.SN,
        countryObject.SO,
        countryObject.TW,
        countryObject.TZ,
        countryObject.VA,
        countryObject.BG,
        countryObject.BH,
        countryObject.AO
    ]
];